version: '3.12.3'
services:
    web:
        image: healthmedia
        build: .
        env_file:
            - .env
        ports:
            - "8891:8891"
        volumes:
            - ./instance:/instance
        restart: unless-stopped